language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run lint
after_script: 
  - |
    if [[ ($TRAVIS_BRANCH == $FRONTEND_DEPLOY_BRANCH ) && ($TRAVIS_PULL_REQUEST == false) ]]; then
        curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
        sh trigger-travis.sh --branch $BACKEND_DEPLOY_BRANCH $BACKEND_GITHUB_ID $BACKEND_REPO_ID $TRAVIS_ACCESS_TOKEN
    else
        echo "Backend deployment did not run"
    fi
    
